### ISSUE TITLE
"Donate" Button behavior on Nav bar

### ISSUE THREAD

**Issue by nandanimal** [nandanimal/lvtf-website#4]
When the nav bar collapses into hamburger menu, the "Donate" button doesn't disappear, and instead centers itself. 

<img width="925" alt="Screen Shot 2020-12-18 at 12 54 18 PM" src="https://user-images.githubusercontent.com/61749625/102660647-36e2c900-4130-11eb-95c4-e12438ab16e1.png">
<img width="729" alt="Screen Shot 2020-12-18 at 12 54 29 PM" src="https://user-images.githubusercontent.com/61749625/102660650-39ddb980-4130-11eb-8686-f23addbbc589.png">

Ideally, all nav bar items disappear when screen width <= 960px, and appear as a list within the hamburger menu.

**Comment by Jc7j** [comment]
Fixed in lastest changes
